package lab7;

import javax.swing.*;
import java.awt.event.*;
import java.io.FileOutputStream;
import java.util.ArrayList;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

public class CertificateGUI extends javax.swing.JFrame {

    private JList<String> certList;
    private JButton downloadButton;
    private DefaultListModel<String> model;
    private String studentID;
    
    public CertificateGUI(String studentID) {
        
    this.studentID = studentID;
        model = new DefaultListModel<>();
        certList = new JList<>(model);
        downloadButton = new JButton("Download PDF");
        JScrollPane scrollPane = new JScrollPane(certList);
        add(scrollPane);
        add(downloadButton, "South");
        setSize(400, 300);
        setTitle("Certificate Earned");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        loadCertificates();

        downloadButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int idx = certList.getSelectedIndex();
                if (idx >= 0) {
                    try {
                        ArrayList<Certificate> certs = CertificateManager.getCertificates(studentID);
                        Certificate selected = certs.get(idx);
                        generatePDF(selected);
                        JOptionPane.showMessageDialog(null, "PDF downloaded!");
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });

        setVisible(true);
    }    

private void loadCertificates() {
        try {
            ArrayList<Certificate> certs = CertificateManager.getCertificates(studentID);
            for (Certificate c : certs) {
                model.addElement(c.getCourseTitle() + " - " + c.getIssueDate());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void generatePDF(Certificate cert) throws Exception {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(cert.getCourseTitle() + "_certificate.pdf"));
        document.open();
        document.add(new Paragraph("Certificate of Completion"));
        document.add(new Paragraph("Course: " + cert.getCourseTitle()));
        document.add(new Paragraph("Student ID: " + cert.getStudentID()));
        document.add(new Paragraph("Certificate ID: " + cert.getCertificateID()));
        document.add(new Paragraph("Issue Date: " + cert.getIssueDate()));
        document.close();
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

