package lab7;

import java.util.ArrayList;
import javax.swing.JOptionPane; // Added for error messages

/**
 *
 * @author fawaa
 */
public class CourseWindowMine extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseWindowMine.class.getName());
    Course course ;
    Student student ;
    ArrayList<Lesson> lessons = new ArrayList<>();

    /**
     * Creates new form CourseWindowMine
     */
    public CourseWindowMine ( Course course , Student student ) {
        this.course = course ;
        this.student = student ;
        this.lessons = course.getLessons() ;

        initComponents();
        // The lessons list is correctly populated here:
        FillLessonChoices();


    }

    // New method to populate the Choice component with lesson titles
    private void FillLessonChoices() {
        choice1.removeAll();
        for (Lesson lesson : lessons) {
            System.out.println("xx");
            choice1.add(lesson.getTitle());
        }
        choice1.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        choice1 = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Changed to DISPOSE to prevent closing entire app

        jButton1.setText("Start its Quiz"); // Button text is correct
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1)
                                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(jButton1)))
                                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    // CourseWindowMine.java

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // FIX: Get the selected INDEX (0, 1, 2, etc.) instead of the item's text (String).
        int choiceIndex = choice1.getSelectedIndex();
        System.out.println(choiceIndex);
        if (choiceIndex == -1) // -1 means nothing is selected
        {
            JOptionPane.showMessageDialog(this, "Please select a lesson!");
            return; // Stop execution if nothing is selected
        }
        if ( lessons.equals(null) )
        {
            System.out.println("here");
        }
        // Use the index to get the correct Lesson object
        Lesson selectedLesson = lessons.get(choiceIndex);

        if ( selectedLesson.equals(null) )
        {
            System.out.println("here2");
        }
        Quiz quiz = selectedLesson.getQuiz();

        // *** FIX START HERE ***
        if (quiz == null) {
            JOptionPane.showMessageDialog(this, "This lesson does not have a quiz available.", "No Quiz", JOptionPane.INFORMATION_MESSAGE);
        } else if (quiz.getQuestions() == null || quiz.getQuestions().isEmpty()) {
            // Also a good idea to check if the quiz has any questions
            JOptionPane.showMessageDialog(this, "The quiz exists but contains no questions.", "No Questions", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Only proceed if the quiz object is not null and has questions
            new QuizFram(quiz).setVisible(true);
            // this.dispose(); // Optional: uncomment if you want to close CourseWindowMine
        }
        // *** FIX END HERE ***
    }

    // Variables declaration - do not modify
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration
}