package lab7;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ListSelectionEvent;
import java.awt.*;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author fawaa
 */
public class StudentDashboardFrame extends javax.swing.JFrame
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName());
    DefaultListModel<Course> modelofcourses = new DefaultListModel<>(); // For Search Results (jList3)
    DefaultListModel<Course> previousCourses = new DefaultListModel<>(); // For Enrolled Courses (jList2)
    /**
     * Creates new form StudentDashboardFrame
     */
    Student student ;
    public StudentDashboardFrame(Student student)
    {
        this.student = student ;
        initComponents();
        // CALL THE METHOD TO LOAD DATA IMMEDIATELY AFTER COMPONENTS ARE INITIALIZED
        loadPreviousCourses();
    }

    // --- NEW METHOD TO LOAD PREVIOUS COURSES ---
    private void loadPreviousCourses() {
        // Clear existing data (important if called multiple times, though usually not needed here)
        previousCourses.clear();
        DefaultListModel<String> previousTitles = new DefaultListModel<>();

        // Assuming 'student.enrolledCourses' is populated upon creating the Student object
        for (Course course : student.getEnrolledCourses())
        {
            previousTitles.addElement(course.getTitle());
            previousCourses.addElement(course); // Store the Course object in the dedicated model
        }

        jList2.setModel(previousTitles);
        // jList2.setVisible(true); // Setting visible is not usually necessary here as JFrame does it
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("YOUR COURSES");

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("SEARCH ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        /*
        jList2.setModel(new AbstractListModel<Course>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
         */
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jList2MouseClicked(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        // Removed jList2ComponentShown logic as it's now handled by loadPreviousCourses()
        // jList2.addComponentListener(new java.awt.event.ComponentAdapter() {
        //     public void componentShown(java.awt.event.ComponentEvent evt) {
        //         jList2ComponentShown(evt);
        //     }
        // });
        jScrollPane2.setViewportView(jList2);

        /*
        jList3.setModel(new AbstractListModel<Course>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
         */
        jList3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jList3MouseClicked(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jList3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jList3ComponentShown(evt);
            }
        });
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel5.setText("HI" + " " + student.getUsername().toUpperCase());
        jLabel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel5ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(247, 247, 247)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane3))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void jLabel5ComponentShown(ComponentEvent evt) {
        // No action needed here
    }

    private void jList3AncestorAdded(AncestorEvent evt)
    {
        // No action needed here
    }
    private void jList3ValueChanged(ListSelectionEvent evt)
    {
        // No action needed here
    }





    // for search (jList3)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String courseTitle = jTextField1.getText().trim();

        if (courseTitle.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter a course tile");
            return;
        }

        // Clear previous search results before adding new ones
        modelofcourses.clear();
        DefaultListModel<String> modeloftitles = new DefaultListModel<>();

        ArrayList<Course> results = student.search(courseTitle);

        if (results == null || results.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No course found");
            return;
        }

        for (Course course : results)
        {
            modelofcourses.addElement(course);
            modeloftitles.addElement(course.getTitle());
        }
        jList3.setModel(modeloftitles);
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // No action needed here
    }
    private void jList3ComponentShown(ComponentEvent evt)
    {
        // write courses according to the search - This is handled in jButton1ActionPerformed
    }

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) throws IOException
    {
        // open course window ?? search
        if (evt.getClickCount() == 2)
        {
            String selectedtitle = jList3.getSelectedValue();
            if (selectedtitle != null)
            {
                Course selectedcourse = null;
                // Iterate through the modelofcourses (the one holding Course objects)
                for (int i = 0; i < modelofcourses.getSize(); i++)
                {
                    if (selectedtitle.equals(modelofcourses.get(i).getTitle()))
                    {
                        selectedcourse = modelofcourses.get(i);
                        break;
                    }
                }
                if (selectedcourse != null) {
                    new CourseWindow(selectedcourse, student).setVisible(true);
                }
            }
        }
    }




    // for previous (jList2)
    private void jList2MouseClicked(java.awt.event.MouseEvent evt) throws IOException
    {
        // open course window 
        if (evt.getClickCount() == 2)
        {
            // Get the selected title from jList2
            String selectedtitle = jList2.getSelectedValue();
            if (selectedtitle != null)
            {
                Course selectedcourse = null;
                // Find the Course object in the previousCourses model
                for (int i = 0; i < previousCourses.getSize(); i++)
                {
                    if (selectedtitle.equals(previousCourses.get(i).getTitle()))
                    {
                        selectedcourse = previousCourses.get(i);
                        break;
                    }
                }

                if (selectedcourse != null) {
                    try {
                        new CourseWindow(selectedcourse, student).setVisible(true);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            }
        }

        // --- REMOVED INCORRECT CODE ---
        // The original code was incorrectly re-populating the list and adding a new listener
        // every time the list was clicked. This is fixed by calling loadPreviousCourses() 
        // in the constructor and keeping the click logic simple.
        
        /* Original incorrect code:
        DefaultListModel<String> previousTitles = new DefaultListModel<>();

        for ( int i = 0 ; i < student.enrolledCourses.size() ; i++ )
        {
            previousTitles.addElement(student.enrolledCourses.get(i).getTitle());
            previousCourses.addElement(student.enrolledCourses.get(i));
        }

        jList2.setModel(previousTitles);
        jList2.setVisible(true);

        jList2.addMouseListener(new java.awt.event.MouseAdapter()
        { ... });
        */
    }

    // This is no longer needed because loadPreviousCourses() is called in the constructor.
    private void jList2ComponentShown(java.awt.event.ComponentEvent evt)
    {
        // DefaultListModel <String> printedTitles = new DefaultListModel<>();
        // for ( int i = 0 ; i < previousCourses.size() ; i++ )
        // {
        //     printedTitles.addElement(previousCourses.get(i).getTitle());
        // }
        // jList2.setModel(printedTitles);
        // jList2.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */




// Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private JList<String> jList2;
    private JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
// End of variables declaration
}
